### ISSUE TITLE
Credo

### ISSUE THREAD

**Issue by Bgarverick** [Bgarverick/NBCUCareer-website#11]
On the right side of the screen under the apply button on the Nextech and Intern pages, copy the credo from the back of our ID badges. Under we can put a link to the full credo

**Comment by kcajmagic** [comment]
@hvemuri I don't think I like have the credo there what do other people think?

**Comment by Bgarverick** [comment]
@kcajmagic I think we should scrap this idea. I don't think it's working on any of the pages

**Comment by kcajmagic** [comment]
This Credo has already been removed from the O&TS page
