### ISSUE TITLE
Make the video slider on the O&TS Page be automatically open on initial load?

### ISSUE THREAD

**Issue by Harout360** [Bgarverick/NBCUCareer-website#16]
I feel like some people might be hesitant from actually taking the second to open the slide-downs. So if we have one open for them at the start I think they'll be more curious

**Comment by kcajmagic** [comment]
Okay, This is an easy fix

**Comment by kcajmagic** [comment]
I fixed the O&TS Page. All you have to do is add `in` in the `panel-body` that you want open
