### ISSUE TITLE
Testimonials 

### ISSUE THREAD

**Issue by Bgarverick** [Bgarverick/NBCUCareer-website#8]
We need to get stories about what it's like to work at NBCUniversal, Considering we're at the end of the internship we should be able to speak on what it's like to work here. Everyone needs to write one, just a short paragraph about your experience here. There is a doc on the drive with other text you can add it to.

**Comment by mdave424** [comment]
I can put testimonials on my page, the C2C internship page. I've left space in the description text.

**Comment by Bgarverick** [comment]
There are some testimonies on the text doc in the drive

**Comment by mdave424** [comment]
added.
